service/backend(Django)/src/transcendence/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
	path("verify_otp/", views.verify_otp, name='verify_otp'),
]

service/backend(Django)/src/transcendence/pong/urls.py
from django.urls import path
from . import views

app_name = "pong"

urlpatterns = [
]

service/backend(Django)/src/transcendence/transcendence/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from index import views

from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('accounts/', include('accounts.urls')),
    path('pong/', include('pong.urls')),
    #Pour servir les medias la fonction serve on lui envoie tout apres media/ garce a l'expr <path:path>
    path('media/<path:path>', serve, {'document_root' : settings.MEDIA_ROOT}),
]

handler404 = views.error_404

urlpatterns += staticfiles_urlpatterns()

service/backend(Django)/src/transcendence/templates/index/friends.html
<!-- Chat Menu -->
<div class="collapse end-0 col-sm-3 pl-0 py-3 pr-3" id="chatMenu" style="z-index: 100;">
	<div class="card" style="overflow: auto; max-height: 70vh;">
		<div class="card-header text-center fw-bold" data-innerText-translate="Friends">
			Friends
		</div>
		<div class="friend-list card-body list-group list-group-flush border-bottom p-0" style="overflow: auto;">
        <!--LISTE AMIS-->
        <!-- La liste d'amis mise à jour sera affichée ici par JavaScript -->
		</div>
		<!--barre recherche-->
		<form id="search-user-form" class="card-footer m-0" method="post">
			{% csrf_token %}
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Username" id="search_username" name="search_username" required data-placeHolder-translate="Username">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
		</form>
		<!--Resultat recherche amis-->
		<div id="search-result" class="card-body list-group list-group-flush p-0" style="overflow: auto;">
			<!--Ici resultat de recherche d'amis-->
		</div>
		<!--DEMANDES AMIS-->
		<div id="demande-amis" class="card-body list-group list-group-flush p-0" style="overflow: auto;">
			<!--Ici les demandes d'amis-->
		</div>
	</div>
</div>
<div class="position-absolute end-0 col-sm-3 pl-0 py-3 pr-3" id="notificationArea" style="z-index: 200;"></div>

service/backend(Django)/src/transcendence/templates/index/header.html
{% load static %}
<nav class="navbar bg-primary shadow" data-bs-theme="dark">
        <div class="container-fluid">
            <a onclick="goToPage('')" role="button" class="navbar-brand fw-bold">Pong</a>
            <div class="navbar justify-content-end" id="navbarColor02">
				<ul class="navbar-nav mb-2 mb-lg-0 mx-2">
					<select id="languageSelect" onchange="changeLanguage(this.value)" class="form-select" data-width="fit">
						<option value="en">EN</option>
						<option value="fr">FR</option>
						<option value="es">ES</option>
					</select>
				</ul>
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <div id="account_dropdown" class="fw-semibold text-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" role="button">
                            <img id="avatar_menu" class="rounded-circle ml-1" src="" style="width:40px; height:40px">
                        </div>
                        <ul class="dropdown-menu dropdown-menu-end position-absolute">
                            <li><a role="button" class="dropdown-item" id="Myaccount-mm" onclick="goToPage('accounts/me/')" data-innerText-translate="My account">My account</a></li>
                            <li><hr class="dropdown-divider"></li>
			    <li><a role="button" class="dropdown-item" id="logout" onclick="goToPage('accounts/username/me/')"" data-innerText-translate="MyProfile">My profile</a></li>
			    <li><hr class="dropdown-divider"></li>
                            <li><a role="button" class="dropdown-item" id="logout" onclick="logout()" data-innerText-translate="Logout">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

	<script>
		var verifyOtpUrl = "{% url 'accounts:verify_otp' %}";
	</script>

    <!-- Modals -->
    {% if otp_modal %}
    <div class="modal fade" id="otpModal" tabindex="-1" aria-labelledby="otpModalLabel" aria-hidden="true">
	    <div class="modal-dialog">
		    <div class="modal-content">
			    <div class="modal-body">
				    <form id="otpForm" method="post">
					    {% csrf_token %}
					    <div class="mb-3">
						    <input type="text" class="form-control" id="otp_code" name="otp_code" required placeholder="Code OTP" data-placeHolder-translate="OTP code">
						    <input type="hidden" name="username" value="{{ username }}">
						    <input type="hidden" name="password" value="{{ password }}">
							{% if show_otp_error %}
								<p  class="text-danger" data-innerText-translate="incorrect password">Code incorrect</p>
							{% endif %}
							{% if show_otp_error2 %}
								<p  class="text-danger" data-innerText-translate="Error checking OTP code">Erreur lors de la vérification du code OTP.</p>
							{% endif %}
						</div>
						<button type="submit" class="btn btn-primary" data-innerText-translate="Confirm">Valider</button>
					</form>
				</div>
			</div>
		</div>
	</div>

<script>
	document.addEventListener("DOMContentLoaded", function() {
		var otpModal = new bootstrap.Modal(document.getElementById('otpModal'), {
			backdrop: 'static',
			keyboard: false
			});
				otpModal.show();
		});
</script>

	{% else %}
	<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
		<div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header justify-content-center">
                    <div class="nav nav-tabs card-header-tabs fs-4 fw-bold" id="nav-tab" role="tablist">
                        <a class="nav-link active" id="nav-login-tab" role="tab" href="#loginTab" data-innerText-translate="Connection">Connexion</a>
                        <a class="nav-link" id="nav-register-tab" role="tab" href="#registerTab" data-innerText-translate="Registration">Inscription</a>
                    </div>
                </div>
			<div class="modal-body">
			<div class="tab-content">
				<div id="loginTab" class="tab-pane fade show active">
					<form id="myForm" class="mt-4 text-center">
					    <div class="form-group mb-3">
                            <input type="text" id="login_username" name="login_username" class="form-control" placeholder="Nom d'utilisateur" data-placeHolder-translate="Username">
                            <div id="error_username" class="text-danger"></div>
					    </div>
					    <div class="form-group mb-3">
						<div class="input-group">
						    <input type="password" id="login_password" name="login_password" class="form-control" placeholder="Mot de passe" autocomplete="on" data-placeHolder-translate="Password">
						    <div class="input-group-append">
							<button class="btn btn-outline-secondary" type="button" id="login_togglePassword"><i class="fas fa-eye"></i></button>
						    </div>
						</div>
						<div id="error_password" class="text-danger"></div>
					    </div>
					    <div class="text-center">
						<button class="btn btn-primary btn-block mb-3" type="button" onclick="login()" data-innerText-translate="Connection">Connexion</button>
					    </div>
					    <div class="text-center">
						<button id="SignInButton" class="btn btn-dark btn-block" type="button" data-innerText-translate="Sign in with 42">Sign in with 42</button>
					    </div>
					</form>
				    </div>
				    <div id="registerTab" class="tab-pane fade">
					    <div class="form-group mb-3">
						    <input type="text" id="firstname" name="firstname" class="form-control" placeholder="Prénom*" data-placeHolder-translate="First name*">
						    <div id="firstname_error" class="text-danger"></div>
						</div>
						<div class="form-group mb-3">
							<input type="text" id="lastname" name="lastname" class="form-control" placeholder="Nom de famille*" data-placeHolder-translate="Family name*">
							<div id="lastname_error" class="text-danger"></div>
						</div>
						<div class="form-group mb-3">
						    <input type="text" id="username" name="username" class="form-control" placeholder="Nom d'utilisateur*" autocomplete="on" data-placeHolder-translate="Username*">
						    <div id="same_username" class="text-danger"></div>
						</div>
					<form id="register_password_from" class="input-group form-group mb-3">
					    <input type="password" id="register_password" name="register_password" class="form-control" placeholder="Mot de passe*" autocomplete="on" data-placeHolder-translate="Password*">
					    <div class="input-group-append">
						<button class="btn btn-outline-secondary" type="button" id="register_togglePassword"><i class="fas fa-eye"></i></button>
					    </div>
					</form>
					<div id="passworderror" class="text-danger"></div>
					<form class="input-group form-group mb-3">
						<input type="password" id="register_password_confirm" name="register_password_confirm" class="form-control" placeholder="Confirmez le mot de passe*" autocomplete="on" data-placeHolder-translate="Confirm password*">
						<div class="input-group-append">
						    <button class="btn btn-outline-secondary" type="button" id="register_togglePassword_confirm"><i class="fas fa-eye"></i></button>
						</div>
					</form>
					<div id="password_confirm_error" class="text-danger"></div>
					<p class="" data-innerText-translate="Select an avatar*">Sélectionnez un avatar*</p>
					<div class="container mb-3">
						<div class="row justify-content-center">
						    <div class="col d-flex justify-content-between" id="image-row">
							<div class="image-container">
							    <img src="/media/avatar/asian.png" alt="Image 1" class="img-fluid image-thumbnail rounded">
							</div>
							<div class="image-container">
							    <img src="/media/avatar/asianwoman.png" alt="Image 2" class="img-fluid image-thumbnail rounded">
							</div>
							<div class="image-container">
							    <img src="/media/avatar/pongplayer.png" alt="Image 3" class="img-fluid image-thumbnail rounded">
							</div>
							<div class="image-container">
							    <img src="/media/avatar/enstein.png" alt="Image 4" class="img-fluid image-thumbnail rounded">
							</div>
						    </div>
						</div>
					</div>
					<input type="hidden" id="avatar_id" name="avatar" accept="image/*">
					<div id="avatar_error" class="text-danger"></div>
					<div id="void" class="text-danger"></div>
					<div class="text-center">
						<button id="register" type="button" class="btn btn-primary mb-3r" onclick="register()" data-innerText-translate="Register">S'enregistrer</button>
					</div>
					<p class="mb-0" id="obligatoire" data-innerText-translate="* Mandatory">* Obligatoires</p>
				</div>
			</div>
			</div>
		</div>
		</div>
	</div>
	{% endif %}
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

service/backend(Django)/src/transcendence/templates/index/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<link rel="stylesheet" href="{% static 'pong/pong.css' %}">
	<link rel="stylesheet" href="{% static 'index/index.css' %}">
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'icons/ft_websocket_rgb_1.ico' %}" />
	<title data-innerText-translate="Index">Index</title>
	<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
	<title>Index</title>
</head>
<body class="d-flex flex-column vh-100 pr-0" style="background-color: rgba(0, 0, 0, .1); overflow-x: hidden;">
	<header>
		{% include 'index/header.html' %}
	</header>
	<!-- Sidebar + Main -->
	<div class="row h-100 no--bs-gutter-x m-0">
		<!-- Sidebar -->
		<aside class="col-sm-2 bg-light shadow p-0">
			<a class="d-flex align-items-center flex-shrink-0 p-3 link-dark text-decoration-none border-bottom">
				<span class="fs-5 fw-semibold" data-innerText-translate="History">History</span>
			</a>
			<div id="history" class="list-group list-group-flush border-bottom" style="overflow: auto;"></div>
		</aside>
		<!-- Pong -->
		<main id="main" class="col-md-7 no--bs-gutter-x p-0">
			<div class="p-3">
				<div id="score" class="bg-black w-100 row fs-1 fw-bold text-white text-center m-0"></div>
				<div id="pong" class="ratio ratio-4x3 bg-black shadow">
					<div class="position-absolute top-0 end-0" style="left: unset; width: unset;">
						<div class="d-flex">
							<div class="form-text text-white m-1" data-innerText-translate="Server">Server</div>
							<div class="form-check form-switch form-check-inline m-1">
								<input id="toggleLocal" class="form-check-input form-check-inline m-0" type="checkbox" onchange="toggleServerLocal(this)">
							</div>
							<div class="form-text text-white m-1" data-innerText-translate="Local">Local</div>
						</div>
					</div>
					<div id="play" class="text-light text-center collapse show">
						<div id="queue_button" class="btn" type="button" style="font-size: 4rem;"><i class="bi bi-shuffle text-light"></i></div>
						<div id="tournament_button" class="btn" type="button" style="font-size: 4rem;"><i class="bi bi-trophy-fill text-light"></i></div>
						<div id="four_players_button" class="btn" type="button" style="font-size: 4rem;"><i class="bi bi-4-circle-fill text-light"></i></div>
					</div>
					<div id="localPlay" class="text-light text-center collapse">
						<div id="localGame" class="btn" type="button" style="font-size: 4rem;" onclick="playLocal(null, null)"><i class="bi bi-play-circle-fill text-light"></i></div>
						<div id="localTournament" class="btn" type="button" style="font-size: 4rem;" onclick="tournamentLocal()"><i class="bi bi-trophy-fill text-light"></i></div>
					</div>
				</div>
			</div>
		</main>
		{% include 'index/friends.html' %}
	</div>

	<script>
		var baseState = "{{ base_state }}";
		localStorage.setItem('baseState', baseState);
		var jwtTokenJson = '{{ jwt_token_json|escapejs }}';
		if (jwtTokenJson && jwtTokenJson.trim() !== '') {
		    var jwtToken = JSON.parse(jwtTokenJson);
		    localStorage.setItem('jwtToken', jwtToken);
		}
    </script>

    <button id="chatMenuButton" type="button" class="btn btn-primary position-fixed bottom-0 end-0 m-3 rounded-circle" data-bs-toggle="collapse" data-bs-target="#chatMenu" aria-expanded="false" aria-controls="chatMenu" style="width: 50px; height: 50px; z-index: 100;">
        <i class="bi bi-people-fill"></i>
    </button>
	<script src="{% static 'tournament.js' %}"></script>
    <script src="{% static 'router.js' %}"></script>
	<script src="{% static 'friendsProfile.js' %}"></script>
	<script src="{% static 'pong/pong.js' %}"></script>
	<script src="{% static 'chat.js' %}"></script>
	<script src="{% static 'history_game.js' %}"></script>
	<script src="{% static 'queue.js' %}"></script>
	<script src="{% static 'myAccount.js' %}"></script>
	<script src="{% static 'modal.js' %}"></script>
	<script src="{% static 'friendsList.js' %}"></script>
	<script src="{% static 'index/ecouteurEvent.js' %}"></script>
	<script src="{% static 'index/index.js' %}"></script>
	<script src="{% static 'translate.js' %}"></script>
	<script src="{% static 'four_players.js' %}"></script>
	<script src="{% static 'pong4.js' %}"></script>
	<script src="{% static 'toggleServerLocal.js' %}"></script>
	<script src="{% static 'localPong.js' %}"></script>
	<script src="{% static 'localTournament.js' %}"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>